 language: android
    sudo: false
    git:
      depth: 3 #将git depth设置相对小的值,加快构建速度
    jdk:
    - oraclejdk8 #lambda表达式支持,如果工程中使用了rxJava等类库时添加
    android:
      components:
      - tools
      - build-tools-23.0.3
      - android-23
      - extra-android-m2repository
      - extra-android-support
    script:
    - "./gradlew assembleRelease"
    before_install:
    - chmod +x gradlew
    - gem install fir-cli #安装fir命令行客户端
    deploy:
      provider: releases
      api_key:
        secure: 4716f3d26457966b5837ffaa4b3d06e714654b56
      file: app/build/outputs/apk/app-release.apk
      skip_cleanup: true
      on:
        repo: JianxunRao/MoqiDump
    after_deploy:
    - fir login 8f68d31a204da27bfcc3747fa11dcbb6 #fir账号的Token
    - fir me #打印身份信息,验证是否登录成功
    - fir p app/build/outputs/apk/app-release.apk #自动发布应用至fir内测平台

























#language: android
#jdk: oraclejdk8
#android:
#  components:
#    - platform-tools
#    - tools
#    - build-tools-25.0.1
#    - android-25
#    - extra-android-m2repository
#
#script:
#  - "./gradlew publishApkDebug"
#
#before_install:
#- ruby -v
#- chmod +x gradlew
#- gem update --system
#- gem install fir-cli
#after_deploy:
#- fir p app/build/outputs/apk/app-debug.apk -T 8f68d31a204da27bfcc3747fa11dcbb6 -c "`git cat-file tag sjc7rE3Fcptu5gPxnpvo`"
#
#deploy:
#  provider: releases
##  user: "lianshangyangguang"
##  password: "525wanmei"
#  api_key:
#    secure: 8f68d31a204da27bfcc3747fa11dcbb6
#  file: app/build/outputs/apk/app-debug.apk
#  skip_cleanup: true
#  on:
#    tags: true
#    all_branches: true